### ISSUE TITLE
[Nuget API Key] Can you provide?

### ISSUE THREAD

**Issue by jeffward01** [romanov/PercentageNET#5]
Hello!

I was setting up CI / CD with GitHub actions - and I need a nuget API key to do this.  I see that you published this previously under your nuget account. 

Can you please create a nuget API key then add it under 'secrets'? I do not think I have the option to do this.

Here are some screenshots and links to help you:
![image](https://user-images.githubusercontent.com/12589359/201541211-ad3b3a84-d8a7-425f-8a83-59e6ac854be3.png)

https://docs.github.com/en/actions/security-guides/encrypted-secrets

Once you add the key, please let me know what the name of the key is (not the value) so that I can add it to the CI / CD pipeline.

Thanks

**Comment by romanov** [comment]
Published as NUGET_API. Please, provide your discord login (with #)

**Comment by jeffward01** [comment]
Thats great!  Talk to you soon

My Discord: `crypto_wizard #0725`

**Comment by jeffward01** [comment]
> Published as NUGET_API. Please, provide your discord login (with #)

What is your Discord handle so I can say hello? im not sure if we connected yet.
